### ISSUE TITLE
How to setup this project locally

### ISSUE THREAD

**Issue by shoaib-eteam** [HU-BCS1/islamic-inheritance-calculator#6]
Hi How to setup this project locally please explain.

**Comment by ducaale** [comment]
Hi, this is just an npm package for calculating inheritance. https://github.com/HU-BCS1/basic-islamic-inheritance-calculator-ui is where this library is being used.

**Comment by shoaib-eteam** [comment]
Can we do setup this package? with same table fields. 
http://inheritance.ilmsummit.org/projects/inheritance/home.aspx

**Comment by ducaale** [comment]
Do you mean to have the same UI or is there a particular feature you think is missing from https://inheritance-calculator.netlify.com?

For me, the biggest feature that is missing now is the ability to list the steps the calculator took so it could later be verified by a Shiekh or Imam.

**Comment by shoaib-eteam** [comment]
yes, want to use same UI of this http://inheritance.ilmsummit.org/projects/inheritance/home.aspx 
because on this some fields are missing.  https://inheritance-calculator.netlify.com/

29 fields on this. http://inheritance.ilmsummit.org/projects/inheritance/home.aspx 
22 fields on this https://inheritance-calculator.netlify.com/

also can you share some simple web format package like php based.

**Comment by ducaale** [comment]
I assume you can read Arabic, am I right?

From https://ar.wikipedia.org/wiki/%D8%B9%D9%84%D9%85_%D8%A7%D9%84%D9%81%D8%B1%D8%A7%D8%A6%D8%B6
>الوارثون من الرجال بالإتفاق عند جماهير الفقهاء بلاخلاف، خمسة عشر
>الوارثات من النساء بالإجماع عشر

If we add those, it would sum to 25 people. subtract المعتق and المعتقة and that gives you 23 people, right? now you have الأخ لأم and الأخت لأم which could be treated as one so that brings down the total number to 22.

**Comment by shoaib-eteam** [comment]
okay, but I just want to know this can we use this package for the web?
https://github.com/HU-BCS1/islamic-inheritance-calculator

because I like this UI and simple functionality.

**Comment by ducaale** [comment]
I am glad you liked the UI. What is your experience in Frontend web development i.e React js, Vue js, etc?

**Comment by shoaib-eteam** [comment]
I am a Frontend web developer, not an idea of any js languages. I want to use this for the web for using a charity website. and that is hosted on wp-engine platform.

**Comment by ducaale** [comment]
If your requirement is to only use PHP, then you can always embed this in an iframe inside your WordPress site. Although you should be aware this library hasn't been verified enough so it might not always give the correct result.

**Comment by shoaib-eteam** [comment]
okay, but how to set up this on localhost or hosting plan?

**Comment by ducaale** [comment]
I think being familiar with node and npm is a prerequisite to using this library. See https://www.digitalocean.com/community/tutorials/how-to-use-node-js-modules-with-npm-and-package-json

**Comment by shoaib-eteam** [comment]
Okay, thanks I will coordinate with the developer for this because i have no idea about this :)
